spring:
  application:
    name: gi3

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gi3
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: always

  flyway:
    baseline-on-migrate: true

jwt:
  secret: "y+ohZZ86fmHdDZH5bW88IKTc62jmlEsHMYsS/2lx73s="

admin:
  secret: "Gi3admin12345678"